#!/usr/bin/env python3
import json, html as H
from collections import defaultdict

def esc(s):
    return H.escape(s)

concepts = [
{"title":"Supervised vs Unsupervised Learning","cat":"Statistical Analysis & Regression","ci":7,"body":"Supervised learning: we have a target variable y to predict (e.g. churn, sales, price). Unsupervised learning: no target variable; we discover patterns. Decision Trees, Linear/Logistic Regression, KNN, Naive Bayes are supervised. K-means clustering and Association Rules are unsupervised."},
{"title":"What is Overfitting and How to Reduce It","cat":"Statistical Analysis & Regression","ci":7,"body":"Overfitting: model memorizes training noise instead of learning general patterns. Signs: low training error but much higher test error. Pre-pruning parameters for decision trees: max_depth (limits splits, smaller=simpler), min_samples_split (min samples to split a node, larger=fewer splits), min_samples_leaf (min samples per leaf, larger=prevents tiny noisy leaves), max_leaf_nodes (caps total leaves), max_features (limits features per split), ccp_alpha (post-pruning strength, larger=more pruning)."},
{"title":"How to Read a Decision Tree Node","cat":"Statistical Analysis & Regression","ci":7,"body":"Each node shows: (1) Split rule e.g. Age<=42.5 - if true go left, else right. (2) samples = % of training data at this node. (3) value = class distribution e.g. [0.905, 0.095] means 90.5% class 0, 9.5% class 1. (4) class = majority class prediction. When proportion=True, value shows proportions; otherwise raw counts."},
{"title":"Entropy vs Gini Impurity","cat":"Statistical Analysis & Regression","ci":7,"body":"criterion='entropy' uses information gain. criterion='gini' (default) uses Gini impurity. Both measure node purity. Usually give similar trees. Entropy tends to produce slightly more balanced splits."},
{"title":"Classification Metrics Explained","cat":"Statistical Analysis & Regression","ci":7,"body":"Accuracy = (TP+TN)/total - misleading with imbalanced classes. Precision = TP/(TP+FP) - of predicted positives, how many were correct? Recall = TP/(TP+FN) - of actual positives, how many did we find? F1 = harmonic mean of precision and recall. ROC AUC = how well model ranks positives above negatives (uses probabilities). Confusion matrix: rows=actual, columns=predicted. Top-left=TN, bottom-right=TP."},
{"title":"Regression Metrics Explained","cat":"Statistical Analysis & Regression","ci":7,"body":"MAE = average |actual-predicted|, treats all errors equally. RMSE = sqrt of average squared errors, penalizes large errors more. R2 = proportion of variance explained. R2=1 is perfect, R2=0 means no better than predicting the mean, R2<0 means worse than the mean."},
{"title":"What is Cross-Validation","cat":"Statistical Analysis & Regression","ci":7,"body":"K-fold CV splits data into k folds. Model trains on k-1 folds, validates on the held-out fold, rotating k times. Each sample gets predicted exactly once. More reliable than a single train/test split. When no hyperparameter tuning, CV score alone estimates generalization well. When tuning with GridSearchCV, tune on training set only, evaluate best model once on hold-out test set."},
{"title":"StratifiedKFold vs KFold","cat":"Statistical Analysis & Regression","ci":7,"body":"StratifiedKFold preserves class proportions in each fold - use for classification. KFold does not preserve proportions - use for regression."},
{"title":"GridSearchCV Workflow","cat":"Statistical Analysis & Regression","ci":7,"body":"Tries every combination in param_grid with k-fold CV on training set. Selects best combination by refit= metric. best_estimator_ is automatically refit on full training set. Evaluate once on hold-out test set. n_jobs=-1 uses all CPU cores."},
{"title":"Why Standardize Features","cat":"Data Cleaning & Preprocessing","ci":1,"body":"Standardization: X_std = (X - mean) / std. After: mean~0, std~1. Why: (1) Distance-based methods (KNN, K-means) are dominated by large-scale features otherwise. (2) Regularized models (Ridge, Logistic Regression) affected by scale. (3) After standardization, regression coefficients become comparable. Always fit scaler on training data only, then transform both train and test."},
{"title":"Why Log-Transform Skewed Features","cat":"Data Cleaning & Preprocessing","ci":1,"body":"Skewed features: most values small, few very large. Gaussian Naive Bayes works better with bell-shaped distributions. log1p(x)=log(1+x) shrinks extremes. Safe for zeros (log1p(0)=0). Cannot handle negatives. Absolute skewness > 3 = strong skew worth transforming."},
{"title":"Feature Engineering Rationale","cat":"Data Cleaning & Preprocessing","ci":1,"body":"Creates new predictors from existing columns. Examples: tenure_days, purchases_per_year, spend_estimate. Add small constant to denominators to avoid /0. Linear regression is linear in parameters not raw inputs - can add log, polynomial, interaction terms. More features do NOT automatically mean better performance."},
{"title":"One-Hot Encoding Explained","cat":"Data Cleaning & Preprocessing","ci":1,"body":"Most sklearn models need numbers not text. One-hot encoding: categorical column becomes multiple 0/1 columns, one per category. Use drop_first=True to avoid multicollinearity in regression (k categories become k-1 columns). For 2-value columns (Yes/No), .map() to single 0/1 is simpler."},
{"title":"Linear Regression Concepts","cat":"Statistical Analysis & Regression","ci":7,"body":"Fits y_hat = theta_0 + theta_1*x1 + theta_2*x2 + ... Minimizes squared errors (OLS). Positive coefficient = feature increases prediction. Cannot compare coefficient sizes unless features are on same scale. After standardization, 1 unit = 1 std dev, making coefficients comparable. No hyperparameters. Ridge adds L2 penalty for regularization."},
{"title":"Logistic Regression Concepts","cat":"Statistical Analysis & Regression","ci":7,"body":"Predicts P(y=1) - a probability. Predicts class 1 if probability >= 0.5. Learned by maximizing likelihood (MLE) = minimizing log loss. Different from linear regression (OLS). Increase max_iter if convergence warning. Use predict_proba()[:,1] for positive class probabilities."},
{"title":"Naive Bayes Concepts","cat":"Statistical Analysis & Regression","ci":7,"body":"Learns feature distributions per class (mean, variance for Gaussian). Combines evidence from all features for class probability. 'Naive' = assumes feature independence given class (rarely true, often works). Sensitive to scale - standardize or log-transform. Class priors reflect training class distribution. Interpret by comparing feature means between classes."},
{"title":"K-Means Clustering Concepts","cat":"Statistical Analysis & Regression","ci":7,"body":"Unsupervised - no target. Groups items into k clusters minimizing SSD/inertia. Always standardize first. Elbow Method: plot SSD vs k, look for bend. n_init=10 runs 10 times, keeps best. Interpret: compare average features per cluster (profiles), check category mix within clusters."},
{"title":"KNN Concepts","cat":"Statistical Analysis & Regression","ci":7,"body":"Memory-based/lazy - stores all training data, predicts by K nearest neighbors. Classification: majority class. Regression: average target. Always standardize. Small K overfits, large K over-smooths. Choose K by plotting test performance vs K. KNN is supervised (unlike K-means)."},
{"title":"Association Rules Concepts","cat":"Statistical Analysis & Regression","ci":7,"body":"Unsupervised, based on counting co-occurrences. Format: IF {antecedent} THEN {consequent}. Support(X) = proportion of transactions with X. Confidence(A->B) = Support(A+B)/Support(A). Lift = Support(A+B)/(Support(A)*Support(B)). Lift>1 = positive association, ~1 = independent, <1 = negative. Leverage = observed - expected co-occurrence. HIGH CONFIDENCE CAN MISLEAD when consequent is very common. Always check lift."},
{"title":"Apriori Algorithm","cat":"Statistical Analysis & Regression","ci":7,"body":"Key principle: if an itemset is NOT frequent, no larger itemset containing it can be frequent. This prunes the search space dramatically. Workflow: (1) Find frequent itemsets (min support). (2) Generate rules (min confidence). (3) Filter by lift>1 and leverage>0."},
{"title":"Train/Test Split Purpose","cat":"Statistical Analysis & Regression","ci":7,"body":"Estimates generalization to unseen data. Model trains on training set, evaluated on unseen test set. test_size=0.2 = 80/20 split. random_state = reproducible. stratify=y for classification to keep class proportions. When using GridSearchCV, tune on training set, evaluate best model once on test set."},
{"title":"Comparing Multiple Models","cat":"Statistical Analysis & Regression","ci":7,"body":"Once data is prepared, same code pattern for any model: model.fit(X_train, y_train), model.predict(X_test), model.predict_proba(X_test). Use same split and evaluation function for fair comparison. The hardest part is often NOT the model - it is cleaning data, handling missing values, and feature engineering."},
{"title":"Predicted vs Actual Plot","cat":"Visualization","ci":6,"body":"Diagonal line = perfect predictions. Points close to line = good. Points far = large errors. Systematic curves away from line = model missing nonlinear relationship."},
{"title":"ROC Curve Interpretation","cat":"Visualization","ci":6,"body":"Plots True Positive Rate vs False Positive Rate at different thresholds. Perfect model hugs top-left (AUC=1.0). Random model = diagonal (AUC=0.5). Higher AUC = better ranking. Needs probabilities not labels."},
{"title":"Complexity Curve Interpretation","cat":"Visualization","ci":6,"body":"Plots train/test error vs model complexity. Train error decreases with complexity. Test error decreases then increases - upturn = overfitting. Sweet spot = lowest test error."},
{"title":"Elbow Method Interpretation","cat":"Visualization","ci":6,"body":"Plots SSD vs k. SSD always decreases. Look for the bend where adding clusters gives diminishing returns. Calculate % drop between k values; when drop becomes small = elbow."},
{"title":"Data Exploration Workflow","cat":"Data Import & File I/O","ci":0,"body":"Before modeling: df.info() for types/nulls, df.describe() for numeric summaries, df.shape for dimensions, value_counts() for categorical distributions, isnull().sum() for missing counts. Histograms show distributions. Heatmaps show correlations."},
{"title":"Comparing Groups Analytically","cat":"Data Selection & Filtering","ci":2,"body":"To compare groups (e.g. Members vs Normal): (1) Filter subsets with df.loc[condition]. (2) Compare describe() for key metrics. (3) Check median (50%) and upper quartile (75%) for typical vs extreme. (4) Plot histograms. (5) Use value_counts(normalize=True) for proportions."},
]

entries = [
{"task":"Load a CSV file into a DataFrame","cat":"Data Import & File I/O","ci":0,"fn":"pd.read_csv()","code":"import pandas as pd\ndf = pd.read_csv('filename.csv')","gotcha":"For Excel use pd.read_excel(). Windows paths need r\"...\".","cmp":"read_csv for .csv, read_excel for .xlsx"},
{"task":"Load an Excel file","cat":"Data Import & File I/O","ci":0,"fn":"pd.read_excel()","code":"df = pd.read_excel('filename.xlsx')","gotcha":"Requires openpyxl. Default reads first sheet.","cmp":""},
{"task":"View first N rows","cat":"Data Import & File I/O","ci":0,"fn":"df.head()","code":"df.head()\ndf.head(3)","gotcha":"Returns a view, does not modify.","cmp":"head() top rows; tail() bottom rows."},
{"task":"View last N rows","cat":"Data Import & File I/O","ci":0,"fn":"df.tail()","code":"df.tail(3)","gotcha":"","cmp":""},
{"task":"Check DataFrame shape","cat":"Data Import & File I/O","ci":0,"fn":"df.shape","code":"df.shape","gotcha":"Attribute not method - no parentheses.","cmp":""},
{"task":"Inspect column types and non-null counts","cat":"Data Import & File I/O","ci":0,"fn":"df.info()","code":"df.info()","gotcha":"Prints to console, returns None.","cmp":"info() types+nulls; describe() numeric stats."},
{"task":"Get summary statistics for numeric columns","cat":"Data Import & File I/O","ci":0,"fn":"df.describe()","code":"df.describe()","gotcha":"Only numeric by default. For objects: df[['col']].describe().","cmp":""},
{"task":"List all column names","cat":"Data Import & File I/O","ci":0,"fn":"df.columns","code":"df.columns","gotcha":"Returns Index object. list(df.columns) for a list.","cmp":""},
{"task":"Fill missing values with column mean","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"fillna(), .mean()","code":"df['Income'].fillna(df['Income'].mean(), inplace=True)","gotcha":"inplace=True modifies original. Without it returns new DataFrame.","cmp":"fillna replaces NaN; dropna removes rows."},
{"task":"Fill missing values with a constant","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"fillna()","code":"df['Experience'].fillna(0, inplace=True)\ndf['County'].fillna('Unknown', inplace=True)","gotcha":"Choose domain-appropriate fill value.","cmp":""},
{"task":"Fill missing values using another column","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"np.where(), .isna()","code":"import numpy as np\ndf['discounted_price'] = np.where(\n    df['discounted_price'].isna(),\n    df['original_price'],\n    df['discounted_price'])","gotcha":"np.where(cond, if_true, if_false) is element-wise.","cmp":""},
{"task":"Drop rows where a column has missing values","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"df.dropna()","code":"df = df.dropna(subset=['score']).copy()","gotcha":"subset= specifies columns. .copy() avoids warnings.","cmp":"dropna removes; fillna replaces."},
{"task":"Drop a column","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"df.drop()","code":"df = df.drop('ID', axis=1)\ndf = df.drop(columns='cogs')","gotcha":"axis=1 columns, axis=0 rows.","cmp":""},
{"task":"Count missing values per column","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"isnull().sum()","code":"df.isnull().sum()","gotcha":"isnull() and isna() are identical.","cmp":""},
{"task":"Create dummy variables (one-hot encoding)","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"pd.get_dummies(), pd.concat()","code":"credit = pd.get_dummies(df['CreditCard'], prefix='credit')\ndf = pd.concat([df, credit], axis=1)\ndf.drop('CreditCard', axis=1, inplace=True)","gotcha":"drop_first=True avoids multicollinearity. dtype=int for 0/1.","cmp":"get_dummies is pandas; OneHotEncoder is sklearn."},
{"task":"One-hot encode multiple columns at once","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"pd.get_dummies()","code":"movie = pd.get_dummies(movie,\n    columns=['genre','country'], dtype=int)","gotcha":"Original columns auto-dropped with columns= param.","cmp":""},
{"task":"Map string values to numeric codes","cat":"Data Cleaning & Preprocessing","ci":1,"fn":".map()","code":"df['CreditCard'] = df['CreditCard'].map({'Yes':1, 'No':0})","gotcha":"Unmapped values become NaN.","cmp":"map() on Series; replace() on DataFrame."},
{"task":"Clip values to a valid range","cat":"Data Cleaning & Preprocessing","ci":1,"fn":".clip()","code":"df['popularity'] = df['popularity'].clip(0, 100)","gotcha":"clip(lower, upper) caps both ends.","cmp":""},
{"task":"Replace out-of-range values with mean","cat":"Data Cleaning & Preprocessing","ci":1,"fn":".loc[], .mean()","code":"df.loc[(df['Age']<13)|(df['Age']>100), 'Age'] = df['Age'].mean()","gotcha":"Mean computed before replacement, so outliers affect it.","cmp":""},
{"task":"Cap percentage columns to 0-100","cat":"Data Cleaning & Preprocessing","ci":1,"fn":".loc[]","code":"for c in percent_cols:\n    df.loc[df[c]<0, c] = 0\n    df.loc[df[c]>100, c] = 100","gotcha":"Always validate rate columns in real data.","cmp":""},
{"task":"Convert column to numeric, coercing errors","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"pd.to_numeric()","code":"df['price'] = pd.to_numeric(df['price'], errors='coerce')","gotcha":"errors='coerce' turns bad strings into NaN.","cmp":""},
{"task":"Convert to datetime and extract parts","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"pd.to_datetime(), .dt","code":"df['dt'] = pd.to_datetime(df['date'], errors='coerce')\ndf['month'] = df['dt'].dt.month\ndf['weekday'] = df['dt'].dt.weekday","gotcha":"weekday: Mon=0..Sun=6. Bad dates become NaT.","cmp":""},
{"task":"Compute days between two dates","cat":"Data Cleaning & Preprocessing","ci":1,"fn":".dt.days","code":"df['days'] = (df['end_dt'] - df['start_dt']).dt.days","gotcha":".dt.days for integer. NaT produces NaN.","cmp":""},
{"task":"Parse time string and extract hour","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"pd.to_datetime(), .dt.hour","code":"t = pd.to_datetime(df['Time'], format='%H:%M')\ndf['Hour'] = t.dt.hour","gotcha":"Specify format= to match your pattern.","cmp":""},
{"task":"Convert boolean to 0/1","cat":"Data Cleaning & Preprocessing","ci":1,"fn":".astype(int)","code":"df['explicit'] = df['explicit'].astype(int)","gotcha":"NaN causes error - fill first.","cmp":""},
{"task":"Standardize numeric features","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"StandardScaler","code":"from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nX_train_s = pd.DataFrame(\n    scaler.fit_transform(X_train), columns=X_train.columns)\nX_test_s = pd.DataFrame(\n    scaler.transform(X_test), columns=X_test.columns)","gotcha":"Fit on train only. transform() on test. fit_transform on test leaks info.","cmp":"fit_transform = fit+transform. transform alone on test."},
{"task":"Log-transform skewed columns","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"np.log1p()","code":"df['col_log'] = np.log1p(df['col'])","gotcha":"log1p(0)=0, safe for zeros. Cannot handle negatives.","cmp":""},
{"task":"Create binary flag from condition","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"np.where()","code":"df['Prefer'] = np.where(df['score']>=6.5, 1, 0)","gotcha":"Returns array, assigns to column fine.","cmp":""},
{"task":"Create polynomial/interaction features","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"arithmetic","code":"df['runtime_sq'] = df['runtime'] ** 2\ndf['spend'] = df['purchases'] * df['avg_order']","gotcha":"Too many can overfit.","cmp":""},
{"task":"Create ratio features safely","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"arithmetic","code":"df['rate'] = df['count'] / (df['years'] + 1e-6)","gotcha":"Small constant in denominator prevents /0.","cmp":""},
{"task":"Identify categorical vs numeric columns","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"select_dtypes()","code":"cat_cols = df.select_dtypes(include=['object']).columns.tolist()\nnum_cols = df.select_dtypes(include=['number']).columns.tolist()","gotcha":"'object' catches strings.","cmp":""},
{"task":"Fill all numeric NaN with means at once","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"fillna(), .mean()","code":"df = df.fillna(df.mean(numeric_only=True))","gotcha":"numeric_only=True skips non-numeric.","cmp":""},
{"task":"Fill NaN with median","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"fillna(), .median()","code":"X = X.fillna(X.median(numeric_only=True))","gotcha":"Median more robust to outliers than mean.","cmp":""},
{"task":"Look up ZIP codes for location","cat":"Data Cleaning & Preprocessing","ci":1,"fn":"pgeocode","code":"import pgeocode\nnomi = pgeocode.Nominatim('us')\nout = nomi.query_postal_code(df['ZIP'].astype(str).tolist())\ndf['County'] = out['county_name'].values","gotcha":"pip install pgeocode. ZIP must be string.","cmp":""},
{"task":"Check column skewness","cat":"Data Cleaning & Preprocessing","ci":1,"fn":".skew()","code":"df[num_cols].skew().sort_values(ascending=False)","gotcha":"Skewness > 3 = strong skew, consider log transform.","cmp":""},
# --- Selection & Filtering ---
{"task":"Select columns by name","cat":"Data Selection & Filtering","ci":2,"fn":"df[[col1, col2]]","code":"df[['Customer type', 'City']]","gotcha":"Double [[ ]] = DataFrame; single [ ] = Series.","cmp":""},
{"task":"Select by integer position","cat":"Data Selection & Filtering","ci":2,"fn":"df.iloc[]","code":"df.iloc[0:2, :3]","gotcha":"Exclusive end: iloc[0:2] = rows 0,1 not 2.","cmp":"iloc = integer position; loc = label name. loc[0:2] includes 2."},
{"task":"Select by label names","cat":"Data Selection & Filtering","ci":2,"fn":"df.loc[]","code":"df.loc[0:2, :'Customer type']","gotcha":"Inclusive end: loc[0:2] = rows 0,1,2.","cmp":"loc label-based; iloc position-based."},
{"task":"Filter rows by a single condition","cat":"Data Selection & Filtering","ci":2,"fn":"df.loc[condition]","code":"df.loc[df['Branch']=='A', 'Customer type']","gotcha":"Use == not =.","cmp":""},
{"task":"Filter rows by multiple conditions (AND/OR)","cat":"Data Selection & Filtering","ci":2,"fn":"df.loc[], & |","code":"df.loc[(df['Branch']=='A') & (df['Qty']>5)]\ndf.loc[(df['Gender']=='F') | (df['Line']=='Health')]","gotcha":"Each condition in parentheses. Use & | not and/or.","cmp":""},
{"task":"Create filtered subset for analysis","cat":"Data Selection & Filtering","ci":2,"fn":"df.loc[]","code":"member_df = df.loc[df['Customer type']=='Member']\nnormal_df = df.loc[df['Customer type']=='Normal']","gotcha":"Use .copy() if you plan to modify the subset.","cmp":""},
{"task":"Separate features (X) and target (y)","cat":"Data Selection & Filtering","ci":2,"fn":"df.drop(), df.iloc[]","code":"X = df.drop('Personal.Loan', axis='columns')\ny = df['Personal.Loan']\n# or:\nX = df.iloc[:, :-1]\ny = df.iloc[:, -1]","gotcha":"Ensure X does not contain the target.","cmp":""},
{"task":"Collect columns matching a prefix","cat":"Data Selection & Filtering","ci":2,"fn":"list comprehension","code":"genre_cols = [c for c in df.columns if c.startswith('genre_')]","gotcha":"Case-sensitive unless you use .lower().","cmp":""},
{"task":"Remove cancellations and invalid rows","cat":"Data Selection & Filtering","ci":2,"fn":"boolean indexing, .str methods","code":"df = df[df['Quantity'] > 0]\ndf = df[~df['InvoiceNo'].astype(str).str.startswith('C')]\ndf = df[~df['Description'].str.contains('POSTAGE', na=False)]","gotcha":"~ is NOT. na=False prevents NaN errors.","cmp":""},
# --- Aggregation & Grouping ---
{"task":"Count occurrences of each unique value","cat":"Aggregation & Grouping","ci":3,"fn":"value_counts()","code":"df['City'].value_counts()","gotcha":"Sorted descending. NaN excluded by default; dropna=False to include.","cmp":"value_counts() counts; nunique() just the count of distinct values."},
{"task":"Get relative frequencies (proportions)","cat":"Aggregation & Grouping","ci":3,"fn":"value_counts(normalize=True)","code":"df['City'].value_counts(normalize=True)","gotcha":"Proportions sum to 1.0.","cmp":""},
{"task":"Count number of unique values","cat":"Aggregation & Grouping","ci":3,"fn":".nunique()","code":"df['Product line'].nunique()","gotcha":"Excludes NaN by default.","cmp":"nunique() = count; unique() = actual values."},
{"task":"List all unique values","cat":"Aggregation & Grouping","ci":3,"fn":".unique()","code":"df['Rating'].unique()","gotcha":"Returns NumPy array. Includes NaN if present.","cmp":""},
{"task":"Describe statistics for column subset","cat":"Aggregation & Grouping","ci":3,"fn":".describe()","code":"member_df[['Total','gross income','Quantity']].describe()","gotcha":"Shows count, mean, std, min, quartiles, max.","cmp":""},
{"task":"Compute aggregates with .agg()","cat":"Aggregation & Grouping","ci":3,"fn":".agg()","code":"df[['Age','Purchases']].agg(['min','max'])","gotcha":"Accepts list of function names or functions.","cmp":""},
{"task":"Group and count with transform","cat":"Aggregation & Grouping","ci":3,"fn":"groupby().transform()","code":"df['album_songs'] = df.groupby(\n    ['artist','album'])['track_id'].transform('count')","gotcha":"transform returns same-length Series for direct assignment.","cmp":"transform broadcasts back; agg collapses groups."},
{"task":"Cumulative count within groups","cat":"Aggregation & Grouping","ci":3,"fn":"groupby().cumcount()","code":"df['song_num'] = df.groupby('artist').cumcount()","gotcha":"Starts at 0. Sort data first.","cmp":"cumcount = running position; transform('count') = total."},
{"task":"Group minimum with transform","cat":"Aggregation & Grouping","ci":3,"fn":"groupby().transform('min')","code":"df['first_year'] = df.groupby('artist')['year'].transform('min')","gotcha":"Broadcasts group min to every row.","cmp":""},
{"task":"Group means for cluster profiling","cat":"Aggregation & Grouping","ci":3,"fn":"groupby().mean()","code":"profile = df.groupby('cluster')[features].mean().round(2)","gotcha":"Only numeric columns.","cmp":""},
{"task":"Combine value_counts from filtered subsets","cat":"Aggregation & Grouping","ci":3,"fn":"value_counts(), pd.concat()","code":"sA = df.loc[df['Branch']=='A','Type'].value_counts(normalize=True)\nsB = df.loc[df['Branch']=='B','Type'].value_counts(normalize=True)\nshares = pd.concat([sA, sB], axis=1)\nshares.columns = ['A','B']","gotcha":"concat axis=1 joins side by side.","cmp":""},
{"task":"Genre distribution within clusters","cat":"Aggregation & Grouping","ci":3,"fn":"value_counts(normalize=True)","code":"for c in sorted(df['cluster'].unique()):\n    print(df.loc[df['cluster']==c,'genre']\n          .value_counts(normalize=True).head(5))","gotcha":"Interpretation step - K-means didn't use genre.","cmp":""},
# --- Merging & Joining ---
{"task":"Concatenate DataFrames vertically (stack rows)","cat":"Merging & Joining","ci":4,"fn":"pd.concat(), axis=0","code":"pd.concat([d1, d2], ignore_index=True, axis=0)","gotcha":"axis=0 stacks rows (default). ignore_index resets index.","cmp":""},
{"task":"Concatenate DataFrames horizontally","cat":"Merging & Joining","ci":4,"fn":"pd.concat(), axis=1","code":"pd.concat([d1, d2], axis=1)","gotcha":"Aligns by index. Mismatched indices produce NaN.","cmp":"concat aligns by index; merge by key columns."},
{"task":"Merge DataFrames on key columns","cat":"Merging & Joining","ci":4,"fn":"df.merge()","code":"df = df.merge(other_df,\n    on=['artist','album'], how='left')","gotcha":"Default how='inner' drops non-matches. how='left' keeps all left rows.","cmp":"merge on column values; concat on index."},
# --- Reshaping ---
{"task":"Pivot long table to wide basket matrix","cat":"Reshaping & Pivoting","ci":5,"fn":"groupby().unstack()","code":"basket = df.groupby(['InvoiceNo','Description'])['Qty']\\\n    .sum().unstack(fill_value=0)\nbasket = (basket > 0).astype(int)","gotcha":"fill_value=0 replaces NaN. unstack moves inner index to columns.","cmp":"unstack inverse of stack. pivot_table alternative."},
{"task":"Transpose a DataFrame","cat":"Reshaping & Pivoting","ci":5,"fn":".T","code":"shares.T","gotcha":"Column names become new index.","cmp":""},
# --- Visualization ---
{"task":"Plot histograms for all numeric columns","cat":"Visualization","ci":6,"fn":"df.hist(), plt.show()","code":"df.hist(figsize=(12,8))\nplt.tight_layout()\nplt.show()","gotcha":"Adjust figsize for readability.","cmp":""},
{"task":"Plot a histogram for a single column","cat":"Visualization","ci":6,"fn":".hist(), plt labels","code":"df['Rating'].hist(bins=20)\nplt.xlabel('Rating')\nplt.ylabel('Frequency')\nplt.show()","gotcha":"Default bins=10. Increase for finer granularity.","cmp":""},
{"task":"Plot a bar chart from value counts","cat":"Visualization","ci":6,"fn":"value_counts().plot(kind='bar')","code":"df['City'].value_counts().plot(kind='bar')\nplt.ylabel('Count')\nplt.show()","gotcha":"kind='bar' vertical; kind='barh' horizontal.","cmp":""},
{"task":"Plot a grouped bar chart comparing categories","cat":"Visualization","ci":6,"fn":".plot(kind='bar')","code":"shares.plot(kind='bar')\nplt.legend(bbox_to_anchor=(1,1))\nplt.show()","gotcha":"bbox_to_anchor moves legend outside plot.","cmp":""},
{"task":"Create a scatter plot to visualize correlation","cat":"Visualization","ci":6,"fn":"plt.scatter()","code":"plt.scatter(df['x'], df['y'])\nplt.xlabel('x')\nplt.ylabel('y')\nplt.show()","gotcha":"Shows relationships, does not prove causation.","cmp":""},
{"task":"Scatter plot with regression trend line","cat":"Visualization","ci":6,"fn":"sns.regplot()","code":"sns.regplot(x='x', y='y', data=df)\nplt.show()","gotcha":"Adds linear fit + 95% CI band by default.","cmp":""},
{"task":"Plot a heatmap of correlations","cat":"Visualization","ci":6,"fn":"sns.heatmap(), .corr()","code":"sns.heatmap(df.corr(numeric_only=True),\n    annot=True, cmap='coolwarm')\nplt.show()","gotcha":"corr() is Pearson (linear only). annot=True prints values.","cmp":""},
{"task":"Plot a confusion matrix","cat":"Visualization","ci":6,"fn":"ConfusionMatrixDisplay","code":"from sklearn.metrics import ConfusionMatrixDisplay\nConfusionMatrixDisplay.from_predictions(y_test, y_pred)\nplt.show()","gotcha":"from_predictions takes actual and predicted labels.","cmp":""},
{"task":"Plot an ROC curve","cat":"Visualization","ci":6,"fn":"RocCurveDisplay","code":"from sklearn.metrics import RocCurveDisplay\nRocCurveDisplay.from_predictions(y_test, y_proba)\nplt.show()","gotcha":"Needs probabilities not class labels. Use predict_proba()[:,1].","cmp":""},
{"task":"Plot predicted vs actual values","cat":"Visualization","ci":6,"fn":"plt.scatter(), plt.plot()","code":"plt.scatter(y_test, y_pred)\nplt.plot([y_test.min(), y_test.max()],\n         [y_test.min(), y_test.max()], 'r--')\nplt.xlabel('Actual')\nplt.ylabel('Predicted')\nplt.show()","gotcha":"Points on diagonal = perfect. Spread = error.","cmp":""},
{"task":"Plot train vs test error (complexity curve)","cat":"Visualization","ci":6,"fn":"plt.plot()","code":"plt.plot(depths, train_err, label='Train')\nplt.plot(depths, test_err, label='Test')\nplt.xlabel('max_depth')\nplt.legend()\nplt.show()","gotcha":"When train drops but test rises = overfitting.","cmp":""},
{"task":"Plot elbow method for K-means","cat":"Visualization","ci":6,"fn":"KMeans.inertia_, plt.plot()","code":"ssds = []\nfor k in range(2, 11):\n    km = KMeans(n_clusters=k, n_init=10, random_state=42)\n    km.fit(X_s)\n    ssds.append(km.inertia_)\nplt.plot(range(2,11), ssds, 'o-')\nplt.xlabel('k')\nplt.ylabel('SSD')\nplt.show()","gotcha":"inertia_ is sum of squared distances. Look for elbow bend.","cmp":""},
{"task":"2D scatter plot colored by cluster","cat":"Visualization","ci":6,"fn":"sns.scatterplot(), hue=","code":"sns.scatterplot(x=X_s[:,0], y=X_s[:,1],\n    hue=labels, palette='Set2')\nplt.show()","gotcha":"hue= colors points by categorical column.","cmp":""},
{"task":"Plot KNN accuracy vs K","cat":"Visualization","ci":6,"fn":"plt.plot()","code":"accs = []\nfor k in range(1, 21):\n    knn = KNeighborsClassifier(n_neighbors=k)\n    knn.fit(X_train_s, y_train)\n    accs.append(knn.score(X_test_s, y_test))\nplt.plot(range(1,21), accs, 'o-')\nplt.xlabel('K')\nplt.ylabel('Accuracy')\nplt.show()","gotcha":"Small K overfits; large K over-smooths.","cmp":""},
{"task":"Plot feature importances","cat":"Visualization","ci":6,"fn":".feature_importances_","code":"imp = pd.Series(model.feature_importances_,\n    index=X.columns).sort_values()\nimp.plot(kind='barh')\nplt.show()","gotcha":"Sums to 1.0. Higher = more important for splitting.","cmp":""},
{"task":"Plot regression coefficients","cat":"Visualization","ci":6,"fn":"pd.Series, .plot(kind='barh')","code":"coefs = pd.Series(model.coef_, index=X.columns)\ncoefs.sort_values().plot(kind='barh')\nplt.show()","gotcha":"Only comparable if features are standardized.","cmp":""},
{"task":"Create subplots for multiple histograms","cat":"Visualization","ci":6,"fn":"plt.subplots(), sns.histplot()","code":"fig, axes = plt.subplots(3, 4, figsize=(14,8))\nfor ax, col in zip(axes.ravel(), num_cols):\n    sns.histplot(df[col], ax=ax)\n    ax.set_title(col)\nplt.tight_layout()\nplt.show()","gotcha":"axes.ravel() flattens 2D array. Turn off unused subplots.","cmp":""},
# --- Statistical Analysis & Regression ---
{"task":"Split data into train and test sets","cat":"Statistical Analysis & Regression","ci":7,"fn":"train_test_split()","code":"from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42)","gotcha":"random_state for reproducibility. test_size=0.2 = 80/20.","cmp":""},
{"task":"Split with stratification","cat":"Statistical Analysis & Regression","ci":7,"fn":"train_test_split(stratify=)","code":"X_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42, stratify=y)","gotcha":"stratify=y preserves class proportions. Essential for imbalanced data.","cmp":""},
{"task":"Train a Decision Tree Classifier","cat":"Statistical Analysis & Regression","ci":7,"fn":"DecisionTreeClassifier(), .fit()","code":"from sklearn.tree import DecisionTreeClassifier\ndt = DecisionTreeClassifier(criterion='entropy', random_state=42)\ndt.fit(X_train, y_train)","gotcha":"criterion='entropy' uses info gain; 'gini' (default) uses Gini impurity.","cmp":""},
{"task":"Train a Decision Tree with pruning","cat":"Statistical Analysis & Regression","ci":7,"fn":"DecisionTreeClassifier(max_depth=, min_samples_leaf=)","code":"dt = DecisionTreeClassifier(\n    max_depth=5, min_samples_leaf=10, random_state=42)\ndt.fit(X_train, y_train)","gotcha":"Smaller max_depth + larger min_samples_leaf = simpler tree.","cmp":""},
{"task":"Train a Decision Tree Regressor","cat":"Statistical Analysis & Regression","ci":7,"fn":"DecisionTreeRegressor(), .fit()","code":"from sklearn.tree import DecisionTreeRegressor\ndtr = DecisionTreeRegressor(random_state=42)\ndtr.fit(X_train, y_train)","gotcha":"Evaluate with MAE/RMSE/R2 not accuracy.","cmp":""},
{"task":"Visualize a decision tree","cat":"Statistical Analysis & Regression","ci":7,"fn":"tree.export_graphviz(), graphviz.Source()","code":"from sklearn import tree\nimport graphviz\ndot = tree.export_graphviz(dt, feature_names=X.columns,\n    class_names=['0','1'], filled=True, proportion=True)\ngraphviz.Source(dot)","gotcha":"max_depth= in export limits viz depth, not actual tree. class_names must be strings.","cmp":""},
{"task":"Check tree complexity","cat":"Statistical Analysis & Regression","ci":7,"fn":".tree_.node_count, .tree_.max_depth","code":"print('Nodes:', dt.tree_.node_count)\nprint('Depth:', dt.tree_.max_depth)","gotcha":"Accessed via .tree_ attribute.","cmp":""},
{"task":"Predict class labels","cat":"Statistical Analysis & Regression","ci":7,"fn":".predict()","code":"y_pred = dt.predict(X_test)","gotcha":"Returns class labels (0/1). For probabilities use predict_proba().","cmp":""},
{"task":"Predict class probabilities","cat":"Statistical Analysis & Regression","ci":7,"fn":".predict_proba()","code":"y_proba = dt.predict_proba(X_test)[:,1]","gotcha":"[:,1] gets positive class probability.","cmp":""},
{"task":"Evaluate with accuracy","cat":"Statistical Analysis & Regression","ci":7,"fn":"accuracy_score()","code":"from sklearn.metrics import accuracy_score\naccuracy_score(y_test, y_pred)","gotcha":"Misleading with imbalanced classes.","cmp":""},
{"task":"Evaluate with precision, recall, F1, AUC","cat":"Statistical Analysis & Regression","ci":7,"fn":"precision_score(), recall_score(), f1_score(), roc_auc_score()","code":"from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score\nprint('Precision:', precision_score(y_test, y_pred, zero_division=0))\nprint('Recall:', recall_score(y_test, y_pred))\nprint('F1:', f1_score(y_test, y_pred))\nprint('AUC:', roc_auc_score(y_test, y_proba))","gotcha":"AUC needs probabilities not labels. zero_division=0 avoids warnings.","cmp":""},
{"task":"Generate a classification report","cat":"Statistical Analysis & Regression","ci":7,"fn":"classification_report()","code":"from sklearn.metrics import classification_report\nprint(classification_report(y_test, y_pred))","gotcha":"Shows precision, recall, F1 per class plus averages.","cmp":""},
{"task":"Compute confusion matrix as DataFrame","cat":"Statistical Analysis & Regression","ci":7,"fn":"confusion_matrix()","code":"from sklearn.metrics import confusion_matrix\npd.DataFrame(confusion_matrix(y_test, y_pred),\n    columns=['Pred 0','Pred 1'], index=['Act 0','Act 1'])","gotcha":"Rows=actual, columns=predicted. TL=TN, BR=TP.","cmp":""},
{"task":"Evaluate regression with MAE, RMSE, R2","cat":"Statistical Analysis & Regression","ci":7,"fn":"mean_absolute_error(), mean_squared_error(), r2_score()","code":"from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\nprint('MAE:', mean_absolute_error(y_test, y_pred))\nprint('RMSE:', np.sqrt(mean_squared_error(y_test, y_pred)))\nprint('R2:', r2_score(y_test, y_pred))","gotcha":"sklearn returns MSE not RMSE - take np.sqrt(). R2 can be negative.","cmp":""},
{"task":"5-fold cross-validation for classification","cat":"Statistical Analysis & Regression","ci":7,"fn":"StratifiedKFold, cross_validate()","code":"from sklearn.model_selection import StratifiedKFold, cross_validate\ncv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\nscores = cross_validate(dt, X, y, cv=cv,\n    scoring=['accuracy','f1','roc_auc'])","gotcha":"StratifiedKFold preserves class proportions.","cmp":""},
{"task":"5-fold cross-validation for regression","cat":"Statistical Analysis & Regression","ci":7,"fn":"KFold, cross_validate()","code":"from sklearn.model_selection import KFold, cross_validate\ncv = KFold(n_splits=5, shuffle=True, random_state=42)\nscores = cross_validate(model, X, y, cv=cv,\n    scoring=['neg_mean_absolute_error','r2'])","gotcha":"sklearn uses NEGATIVE MAE for CV. Multiply by -1.","cmp":""},
{"task":"Get out-of-fold predictions","cat":"Statistical Analysis & Regression","ci":7,"fn":"cross_val_predict()","code":"from sklearn.model_selection import cross_val_predict\ny_cv = cross_val_predict(dt, X, y, cv=cv)","gotcha":"Each sample predicted by model that didn't train on it.","cmp":""},
{"task":"Tune hyperparameters with GridSearchCV","cat":"Statistical Analysis & Regression","ci":7,"fn":"GridSearchCV()","code":"from sklearn.model_selection import GridSearchCV\nparam_grid = {'max_depth':[3,5,7], 'min_samples_leaf':[5,10,20]}\ngrid = GridSearchCV(dt, param_grid, cv=5,\n    scoring='f1', refit='f1', n_jobs=-1)\ngrid.fit(X_train, y_train)","gotcha":"refit= selects metric. n_jobs=-1 uses all cores. Tune on train only.","cmp":""},
{"task":"Inspect GridSearchCV results","cat":"Statistical Analysis & Regression","ci":7,"fn":"grid.cv_results_","code":"results = pd.DataFrame(grid.cv_results_)\nresults.sort_values('rank_test_score').head()","gotcha":"Contains mean/std scores for every combination.","cmp":""},
{"task":"Train Linear Regression","cat":"Statistical Analysis & Regression","ci":7,"fn":"LinearRegression(), .fit()","code":"from sklearn.linear_model import LinearRegression\nlr = LinearRegression()\nlr.fit(X_train, y_train)","gotcha":"No hyperparameters (OLS). Minimizes squared error.","cmp":""},
{"task":"Interpret linear regression coefficients","cat":"Statistical Analysis & Regression","ci":7,"fn":".coef_, pd.Series","code":"pd.Series(lr.coef_, index=X.columns).sort_values()","gotcha":"Only comparable if features standardized.","cmp":""},
{"task":"Train Logistic Regression","cat":"Statistical Analysis & Regression","ci":7,"fn":"LogisticRegression(), .fit()","code":"from sklearn.linear_model import LogisticRegression\nlg = LogisticRegression(max_iter=1000, random_state=42)\nlg.fit(X_train, y_train)","gotcha":"Increase max_iter if convergence warning.","cmp":""},
{"task":"Train Gaussian Naive Bayes","cat":"Statistical Analysis & Regression","ci":7,"fn":"GaussianNB(), .fit()","code":"from sklearn.naive_bayes import GaussianNB\nnb = GaussianNB()\nnb.fit(X_train, y_train)","gotcha":"Assumes feature independence. Sensitive to scale.","cmp":""},
{"task":"Inspect Naive Bayes class priors","cat":"Statistical Analysis & Regression","ci":7,"fn":".class_prior_, .classes_","code":"print('Classes:', nb.classes_)\nprint('Priors:', nb.class_prior_)","gotcha":"Reflects training class distribution.","cmp":""},
{"task":"Compare feature means between classes","cat":"Statistical Analysis & Regression","ci":7,"fn":"groupby, mean difference","code":"means = df.groupby('target')[features].mean()\n(means.loc[1] - means.loc[0]).sort_values()","gotcha":"Positive = feature higher for class 1.","cmp":""},
{"task":"Train K-Means clustering","cat":"Statistical Analysis & Regression","ci":7,"fn":"KMeans(), .fit_predict()","code":"from sklearn.cluster import KMeans\nkm = KMeans(n_clusters=4, n_init=10, random_state=42)\nlabels = km.fit_predict(X_s)","gotcha":"Unsupervised. n_init=10 runs 10 times. Always standardize.","cmp":""},
{"task":"Compute SSD decrease per K","cat":"Statistical Analysis & Regression","ci":7,"fn":"inertia_, percentage drop","code":"for i in range(1, len(ssds)):\n    drop = (ssds[i-1]-ssds[i])/ssds[i-1]*100\n    print(f'k={i+2}: {drop:.1f}% drop')","gotcha":"When drop becomes small = elbow.","cmp":""},
{"task":"Train KNN Classifier","cat":"Statistical Analysis & Regression","ci":7,"fn":"KNeighborsClassifier(), .fit()","code":"from sklearn.neighbors import KNeighborsClassifier\nknn = KNeighborsClassifier(n_neighbors=5)\nknn.fit(X_train_s, y_train)","gotcha":"Distance-based - always standardize. Small K overfits.","cmp":""},
{"task":"Train KNN Regressor","cat":"Statistical Analysis & Regression","ci":7,"fn":"KNeighborsRegressor(), .fit()","code":"from sklearn.neighbors import KNeighborsRegressor\nknn_r = KNeighborsRegressor(n_neighbors=5)\nknn_r.fit(X_train_s, y_train)","gotcha":"Predicts average of K neighbors' targets.","cmp":""},
{"task":"Compare multiple classifiers","cat":"Statistical Analysis & Regression","ci":7,"fn":"model loop","code":"for name, model in [('DT', dt), ('LR', lg), ('NB', nb)]:\n    model.fit(X_train, y_train)\n    pred = model.predict(X_test)\n    print(name, accuracy_score(y_test, pred))","gotcha":"Use same split for fair comparison.","cmp":""},
{"task":"Sweep a hyperparameter and plot","cat":"Statistical Analysis & Regression","ci":7,"fn":"loop, accuracy_score","code":"for d in range(1, 20):\n    dt = DecisionTreeClassifier(max_depth=d)\n    dt.fit(X_train, y_train)\n    train_acc.append(dt.score(X_train, y_train))\n    test_acc.append(dt.score(X_test, y_test))","gotcha":"Manual alternative to GridSearchCV for one param.","cmp":""},
{"task":"Find frequent itemsets with Apriori","cat":"Statistical Analysis & Regression","ci":7,"fn":"apriori()","code":"from mlxtend.frequent_patterns import apriori\nfreq = apriori(basket, min_support=0.02, use_colnames=True)","gotcha":"Input must be boolean/0-1 DataFrame. min_support too low = slow.","cmp":""},
{"task":"Generate association rules","cat":"Statistical Analysis & Regression","ci":7,"fn":"association_rules()","code":"from mlxtend.frequent_patterns import association_rules\nrules = association_rules(freq, metric='confidence',\n    min_threshold=0.3)\nrules = rules[rules['lift'] > 1]","gotcha":"High confidence misleads if consequent common. Check lift>1.","cmp":""},
{"task":"Build product recommendations","cat":"Statistical Analysis & Regression","ci":7,"fn":"frozenset filtering","code":"item = frozenset(['ITEM_NAME'])\nrecs = rules[rules['antecedents']==item]\\\n    .sort_values('lift', ascending=False)","gotcha":"antecedents/consequents are frozensets.","cmp":""},
{"task":"Find recommendations for multi-item cart","cat":"Statistical Analysis & Regression","ci":7,"fn":"frozenset, .issubset()","code":"cart = frozenset(['A','B'])\nrecs = rules[rules['antecedents'].apply(\n    lambda x: x.issubset(cart))]","gotcha":"issubset checks if antecedent fully in cart.","cmp":""},
{"task":"Compute association metrics manually","cat":"Statistical Analysis & Regression","ci":7,"fn":"counting, arithmetic","code":"sup_A = (basket['A']==1).mean()\nsup_B = (basket['B']==1).mean()\nsup_AB = ((basket['A']==1)&(basket['B']==1)).mean()\nconf = sup_AB / sup_A\nlift = sup_AB / (sup_A * sup_B)","gotcha":"Lift~1=independent. Lift>1=positive. Leverage>0=exceeds expectation.","cmp":""},
{"task":"Encode transactions into boolean basket","cat":"Statistical Analysis & Regression","ci":7,"fn":"TransactionEncoder","code":"from mlxtend.preprocessing import TransactionEncoder\nte = TransactionEncoder()\nbasket = pd.DataFrame(te.fit_transform(transactions),\n    columns=te.columns_)","gotcha":"Converts list of lists into boolean DataFrame.","cmp":""},
{"task":"Interpret a decision tree node","cat":"Statistical Analysis & Regression","ci":7,"fn":"tree visualization","code":"# Read from tree plot:\n# Split rule, samples %, value (proportions), class","gotcha":"value shows proportions when proportion=True, else raw counts.","cmp":""},
{"task":"Weighted precision/recall/F1 for multi-class","cat":"Statistical Analysis & Regression","ci":7,"fn":"precision_score(average='weighted')","code":"precision_score(y_test, y_pred, average='weighted')\nrecall_score(y_test, y_pred, average='weighted')\nf1_score(y_test, y_pred, average='weighted')","gotcha":"'weighted' weights by support. 'macro' = equal weight per class.","cmp":""},
# --- String & Text Operations ---
{"task":"Split a string by delimiter","cat":"String & Text Operations","ci":8,"fn":".split()","code":"'hello world'.split()\n'a,b,c'.split(',')","gotcha":"No argument splits on whitespace.","cmp":""},
{"task":"Slice a string to extract substring","cat":"String & Text Operations","ci":8,"fn":"string[start:stop]","code":"s = 'Python'\ns[0:3]  # 'Pyt'","gotcha":"Exclusive of stop index.","cmp":""},
{"task":"Convert string to upper/lowercase","cat":"String & Text Operations","ci":8,"fn":".upper(), .lower()","code":"'hello'.upper()  # 'HELLO'\n'HELLO'.lower()  # 'hello'","gotcha":"Returns new string; originals immutable.","cmp":""},
{"task":"Concatenate strings with type conversion","cat":"String & Text Operations","ci":8,"fn":"+ operator, str()","code":"'Age: ' + str(25)","gotcha":"Must convert numbers with str() before + concat.","cmp":""},
{"task":"Count words in a text column","cat":"String & Text Operations","ci":8,"fn":".str.split().str.len()","code":"df['word_count'] = df['text'].astype(str).str.split().str.len()","gotcha":"astype(str) prevents NaN errors.","cmp":""},
{"task":"Check if column contains a keyword","cat":"String & Text Operations","ci":8,"fn":".str.contains()","code":"df[df['desc'].str.contains('sale', case=False, na=False)]","gotcha":"case=False = case-insensitive. na=False for NaN safety.","cmp":""},
{"task":"Fill missing string descriptions with fallback","cat":"String & Text Operations","ci":8,"fn":".fillna()","code":"df['desc'] = df['desc'].fillna(df['title'])","gotcha":"fillna accepts a Series - fills row by row.","cmp":""},
# --- Other (Python basics) ---
{"task":"Basic arithmetic in Python","cat":"Other","ci":9,"fn":"+ - * / // **","code":"10 / 3   # 3.333\n10 // 3  # 3\n2 ** 3   # 8","gotcha":"/ always float. // rounds DOWN: -3//2 = -2.","cmp":""},
{"task":"Use comparison operators","cat":"Other","ci":9,"fn":"==, !=, >=, <=","code":"x == 5\nx != 3\nx >= 10","gotcha":"== checks equality; = is assignment.","cmp":""},
{"task":"Conditional logic with if/elif/else","cat":"Other","ci":9,"fn":"if, elif, else","code":"if score >= 90:\n    grade = 'A'\nelif score >= 80:\n    grade = 'B'\nelse:\n    grade = 'C'","gotcha":"Use and/or in if, not &/|. &/| for pandas Series.","cmp":""},
{"task":"Create and manipulate a list","cat":"Other","ci":9,"fn":"list, .append(), len()","code":"nums = [1, 2, 3]\nnums.append(4)\nlen(nums)  # 4\nnums[-1]   # 4","gotcha":"Index starts at 0. -1 is last element.","cmp":""},
{"task":"Combine two lists","cat":"Other","ci":9,"fn":"+ operator","code":"[1,2] + [3,4]  # [1,2,3,4]","gotcha":"Creates new list; does not modify originals.","cmp":""},
{"task":"Loop through a list with range","cat":"Other","ci":9,"fn":"for, range(), len()","code":"for i in range(len(nums)):\n    print(i, nums[i])","gotcha":"range(n) = 0..n-1. range(i,j) = i..j-1.","cmp":""},
{"task":"Check variable type","cat":"Other","ci":9,"fn":"type()","code":"type(42)       # <class 'int'>\ntype('hello')  # <class 'str'>","gotcha":"Use isinstance() for type checking in conditions.","cmp":""},
{"task":"Convert between numeric types","cat":"Other","ci":9,"fn":"float(), int(), str()","code":"float('3.14')  # 3.14\nint(3.7)       # 3\nstr(42)        # '42'","gotcha":"int() truncates toward zero, does not round.","cmp":""},
{"task":"Define a reusable function","cat":"Other","ci":9,"fn":"def, return","code":"def greet(name):\n    return 'Hello ' + name","gotcha":"Must be defined before called. return sends output back.","cmp":""},
]

confused_pairs = [
("iloc vs loc", "iloc uses integer positions (exclusive end); loc uses label names (inclusive end)."),
("head() vs tail()", "head() shows first N rows; tail() shows last N rows."),
("info() vs describe()", "info() shows column types and non-null counts; describe() shows numeric summary statistics."),
("fillna() vs dropna()", "fillna() replaces missing values; dropna() removes rows/columns with missing values."),
("value_counts() vs nunique()", "value_counts() returns counts per unique value; nunique() returns just the count of distinct values."),
("unique() vs nunique()", "unique() returns the actual distinct values; nunique() returns how many there are."),
("pd.concat() vs pd.merge()", "concat joins by index (axis=0 stacks rows, axis=1 stacks columns); merge joins by matching key column values."),
("axis=0 vs axis=1", "axis=0 operates along rows (vertically); axis=1 operates along columns (horizontally)."),
("predict() vs predict_proba()", "predict() returns class labels; predict_proba() returns probability estimates for each class."),
("fit_transform() vs transform()", "fit_transform() learns parameters and transforms (training data); transform() applies learned parameters (test data)."),
("get_dummies() vs LabelEncoder", "get_dummies creates multiple 0/1 columns (one-hot); LabelEncoder assigns a single integer per category."),
("DecisionTreeClassifier vs DecisionTreeRegressor", "Classifier predicts categories (accuracy/F1); Regressor predicts numbers (MAE/RMSE/R2)."),
("KNeighborsClassifier vs KNeighborsRegressor", "Classifier predicts majority class among K neighbors; Regressor predicts average target of K neighbors."),
("Linear vs Logistic Regression", "Linear predicts a continuous number (minimizes squared error); logistic predicts class probability (maximizes likelihood)."),
("Naive Bayes vs Logistic Regression", "Naive Bayes assumes feature independence and learns distributions; logistic regression directly models the decision boundary."),
("StratifiedKFold vs KFold", "StratifiedKFold preserves class proportions (classification); KFold does not (regression)."),
("cross_validate() vs cross_val_predict()", "cross_validate returns metric scores per fold; cross_val_predict returns actual out-of-fold predictions."),
("GridSearchCV vs manual sweep", "GridSearchCV automates all combinations with CV; manual sweep loops over one parameter."),
("Support vs Confidence vs Lift", "Support = frequency of itemset; Confidence = P(B|A); Lift = observed/expected co-occurrence."),
("K-means vs KNN", "K-means is unsupervised clustering; KNN is supervised prediction using nearest labeled neighbors."),
("Pre-pruning vs Post-pruning", "Pre-pruning sets limits before training (max_depth); post-pruning (ccp_alpha) removes branches after."),
("MAE vs RMSE", "MAE treats all errors equally; RMSE penalizes large errors more."),
("and/or vs &/|", "Use and/or in Python if/else; use &/| for element-wise pandas Series operations (with parentheses)."),
("transform() vs agg()", "transform broadcasts group result back to every original row; agg collapses each group into one row."),
]

# ── Category ordering ──
cat_order = [
    "Data Import & File I/O",
    "Data Cleaning & Preprocessing",
    "Data Selection & Filtering",
    "Aggregation & Grouping",
    "Merging & Joining",
    "Reshaping & Pivoting",
    "Visualization",
    "Statistical Analysis & Regression",
    "String & Text Operations",
    "Other",
]

# ── Group entries by category ──
by_cat = defaultdict(list)
for e in entries:
    by_cat[e["cat"]].append(e)

# ── Group concepts by category ──
concepts_by_cat = defaultdict(list)
for c in concepts:
    concepts_by_cat[c["cat"]].append(c)

# ── Build HTML ──
lines = []
lines.append("""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MM5425 Quick Review</title>
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#fff;color:#333;line-height:1.6;padding:20px;max-width:900px;margin:0 auto}.nav{text-align:center;margin-bottom:12px;font-size:14px}.nav a{color:#4a6fa5;text-decoration:none;font-weight:600}.nav a:hover{text-decoration:underline}h1{text-align:center;color:#2c3e50;margin-bottom:4px;font-size:1.5em}.sub{text-align:center;color:#666;margin-bottom:20px;font-size:.9em}h2{color:#2c3e50;border-bottom:2px solid #4a6fa5;padding-bottom:4px;margin:24px 0 12px 0;font-size:1.15em}table{width:100%;border-collapse:collapse;margin-bottom:16px;font-size:.88em}th{background:#4a6fa5;color:#fff;padding:6px 10px;text-align:left;font-weight:600}td{padding:6px 10px;border-bottom:1px solid #e0e0e0;vertical-align:top}tr:nth-child(even){background:#f8f9fb}.fn{font-family:Consolas,'SFMono-Regular',monospace;font-size:.85em;color:#4527a0}.go{color:#b71c1c;font-size:.85em}.confused{margin-top:30px}.confused table td:first-child{font-weight:600;white-space:nowrap;width:30%}@media print{body{padding:10px;font-size:11px}h1{font-size:1.3em}h2{font-size:1em;margin:14px 0 8px}table{font-size:.8em;page-break-inside:auto}td,th{padding:4px 6px}tr{page-break-inside:avoid}}</style>
</head>
<body>
<div class="nav"><a href="repository.html">&#8594; Code Repository</a></div>
<h1>MM5425 Quick Review Sheet</h1>
<p class="sub">One-page mental walkthrough &mdash; what tool for what job</p>""")

for cat in cat_order:
    rows = by_cat.get(cat, [])
    if not rows:
        continue
    lines.append(f'<h2>{esc(cat)}</h2>')
    lines.append('<table><tr><th>Task</th><th>Key Functions</th><th>Gotcha</th></tr>')
    for e in rows:
        lines.append(f'<tr><td>{esc(e["task"])}</td>'
                     f'<td class="fn">{esc(e["fn"])}</td>'
                     f'<td class="go">{esc(e.get("gotcha",""))}</td></tr>')
    lines.append('</table>')

# Commonly Confused Pairs
lines.append('<div class="confused"><h2>Commonly Confused Pairs</h2>')
lines.append('<table><tr><th>Pair</th><th>Distinction</th></tr>')
for pair, distinction in confused_pairs:
    lines.append(f'<tr><td>{esc(pair)}</td><td>{esc(distinction)}</td></tr>')
lines.append('</table></div>')

lines.append('\n</body>\n</html>')

html = '\n'.join(lines)
with open('review.html', 'w') as f:
    f.write(html)

print(f"Generated review.html ({len(html)} bytes, {html.count('<tr>')} rows)")
